### PR TITLE
bq769x0: Refactor read functions and fix CRC calculation

### LINKED ISSUE #53: bq769x0: repeat read due to crc fail might read different bytes an might led to wrong data read
line 140 will probably try reading a different byte after the crc check failed -> there might be wrong date

https://github.com/LibreSolar/bms-firmware/blob/aa2203aedb176e5c9566f8ba862edca976f1ea4c/drivers/bms_ic/bq769x0/bq769x0.c#L139-L150

you might want to extend the loop to include a reg-addr write before the read retry

### PR DESCRIPTION
**Pull request by martinjaeger**
Use the same function for reading bytes and words.

Fixes #53

Testing with hardware still to be done.

### CODE REVIEW

File: drivers/bms_ic/bq769x0/bq769x0.c [hunk 1]
```diff
@@ -120,94 +120,67 @@ int bq769x0_write_byte(const struct device *dev, uint8_t reg_addr, uint8_t data)
...
     }
 
     if (dev_data->crc_enabled) {
-        /* CRC is calculated over the slave address (incl. R/W bit) and data */
-        buf[0] = (dev_config->i2c.addr << 1) | 1U;
-        int attempts = 1;
-        while (true) {
-            err = i2c_read_dt(&dev_config->i2c, buf + 1, 2);
+        for (int attempts = 1; attempts <= BQ769X0_READ_MAX_ATTEMPTS; attempts++) {
+            err = i2c_write_read_dt(&dev_config->i2c, &reg_addr, 1, buf + 1, num_bytes);
```
Comment (kfessel) [inline drivers/bms_ic/bq769x0/bq769x0.c:139]: you need to read double the num_bytes ( data crc data crc )

Comment (martinjaeger) [reply drivers/bms_ic/bq769x0/bq769x0.c]: Good spot, thanks! Fixed.

**Review by kfessel — COMMENTED** [review]
looks good
